version: '3.7'

services:
  main:
    container_name: 'bookstore_api'
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: ./start-file
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      # - redis
      - postgres

  # redis:
  #   container_name: redis
  #   image: redis:5
  #   networks:
  #     - webnet

  postgres:
    container_name: bookstore_db
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    # healthcheck:
    #   start_period: 40sx



networks:
  webnet:
volumes:
  pgdata: