#!/bin/sh

# install new dependencies if any
yarn

# uninstall the current bcrypt modules
yarn remove bcrypt

# install the bcrypt modules for the machine
yarn add bcrypt

# yarn run migration:generate auto

yarn run migration:run

echo "Starting API server"

yarn run start:dev